test theory

diff --git a/.github/workflows/custom.yml b/.github/workflows/custom.yml
--- a/.github/workflows/custom.yml
+++ b/.github/workflows/custom.yml
@@ -2,27 +2,29 @@ name: Custom Tasks
 
 on:
   workflow_dispatch:
-    inputs:
-      os:
-        description: 'Windows OS Version'
-        required: false
-        default: "2022"
-        type: choice
-        options:
-          - "2025"
-          - "2022"
-          - "2019"
 
 permissions: write-all
 
 jobs:
   testjob:
+    strategy:
+      matrix:
+        test: [1, 2, 3]
+    continue-on-error: ${{ matrix.test % 2 == 1 }} # all even jobs should pass
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v2
-        with:
-          path: netperfrepo
-      - name: Install powershell 7 on Linux
-        run: sudo bash ./netperfrepo/install-pwsh.sh
-        shell: bash
+      - name: odd fail, even pass
+        run: |
+          if [ ${{ matrix.test }} % 2 -eq 0 ]; then
+            echo "even, passing"
+          else
+            echo "odd, fail."
+            exit 1
+          fi
+
+  upload-data:
+    needs: testjob
+    runs-on: ubuntu-latest
+    steps:
+      - name: Upload data
+        run: echo "Uploading data"
