try installing powershell in the job itself

diff --git a/.github/workflows/custom.yml b/.github/workflows/custom.yml
--- a/.github/workflows/custom.yml
+++ b/.github/workflows/custom.yml
@@ -16,122 +16,189 @@ on:
 permissions: write-all
 
 jobs:
-  build-windows:
-    name: Build WinUser
+  build-unix:
+    name: Build Unix
     needs: []
     strategy:
       fail-fast: false
       matrix:
-        os: ['windows-2022']
-        tls: [schannel] # , openssl, openssl3]
-    uses: microsoft/msquic/.github/workflows/build-reuse-win.yml@main
+        os: ['ubuntu-20.04']
+        tls: [openssl] # , openssl3]
+    uses: microsoft/msquic/.github/workflows/build-reuse-unix.yml@main
     with:
       os: ${{ matrix.os }}
       tls: ${{ matrix.tls }}
       build: -Perf
       ref: ${{ github.event.client_payload.sha || github.event.client_payload.ref || inputs.ref || 'main' }}
 
+
   testjob:
-    needs: [build-windows]
+    needs: [build-unix]
     strategy:
       matrix:
         role: ["client", "server"]
-    runs-on: [self-hosted, 1ES.Pool=netperf-boosted-windows-pool]
+    runs-on: [self-hosted, 1ES.Pool=netperf-boosted-linux-pool]
     steps:
-      - name: Get WinRM info
-        run: Get-Service WinRM
-        shell: pwsh
-
-      - name: WinRM quickconfig
-        run: echo Y | winrm quickconfig
-        shell: pwsh
-
-      - name: Enable remote powershell
-        run: Enable-PSRemoting -Force
-        shell: pwsh
-
-      - name: Disable Windows Defender / Firewall
+      - name: Install powershell
         run: |
-          # Disable Windows defender / firewall.
-          Write-Host "Disabling Windows Defender / Firewall."
-          netsh.exe advfirewall set allprofiles state off
-          Set-MpPreference -EnableNetworkProtection Disabled
-          Set-MpPreference -DisableDatagramProcessing $True
-        shell: pwsh
+          # Update the list of packages
+          sudo apt-get update
+          # Install pre-requisite packages.
+          sudo apt-get install -y wget apt-transport-https software-properties-common
+          # Download the Microsoft repository GPG keys
+          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release --release --short)/packages-microsoft-prod.deb
+          # Register the Microsoft repository GPG keys
+          sudo dpkg -i packages-microsoft-prod.deb
+          # Update the list of products
+          sudo apt-get update
+          # Enable the "universe" repositories
+          sudo add-apt-repository --yes universe
 
-      - name: Enabling ServiceLogonRight
-        run: |
-          # Make sure the user has the rights to log on.
-          function Add-ServiceLogonRight ($Username) {
-              $tmp = New-TemporaryFile
-              secedit /export /cfg "$tmp.inf" | Out-Null
-              (Get-Content -Encoding ascii "$tmp.inf") -replace '^SeServiceLogonRight .+', "`$0,$Username" | Set-Content -Encoding ascii "$tmp.inf"
-              secedit /import /cfg "$tmp.inf" /db "$tmp.sdb" | Out-Null
-              secedit /configure /db "$tmp.sdb" /cfg "$tmp.inf" | Out-Null
-              Remove-Item $tmp* -ErrorAction SilentlyContinue
-          }
-          Write-Host "Enabling ServiceLogonRight."
-          Add-ServiceLogonRight -Username "secnetperf"
-        shell: pwsh
+          # Check if PowerShell is available in the repository
+          if apt-cache policy powershell | grep -q "Candidate:"; then
+              echo "PowerShell is available in the repository. Installing..."
+              # Install PowerShell from the repository
+              sudo apt-get install -y powershell
+          else
+              echo "PowerShell is not available in the repository. Falling back to manual installation..."
 
-      - name: Set local user
-        run: Set-LocalUser -Name "secnetperf" -PasswordNeverExpires $true
-        shell: pwsh
+              # Ensure we have the tools for GitHub communication
+              sudo apt-get install -y curl jq
 
+              # Create a temporary directory
+              tmpDir=$(mktemp -d)
+
+              # Fetch the latest release version of PowerShell from GitHub
+              latest_version=$(curl -sSL https://api.github.com/repos/PowerShell/PowerShell/releases/latest | jq -r .tag_name)
+
+              # Download the PowerShell package file
+              echo "Downloading PowerShell package..."
+              downloadUrl=$(curl -sSL "https://api.github.com/repos/PowerShell/PowerShell/releases/latest" |
+                  jq -r '[.assets[] | select(.name | endswith("_amd64.deb")) | .browser_download_url][0]')
+              curl -sSL "$downloadUrl" -o "$tmpDir/powershell.deb"
+
+              # Download the hash file
+              echo "Downloading hash file..."
+              curl -sSL "https://github.com/PowerShell/PowerShell/releases/download/$latest_version/hashes.sha256" -o "$tmpDir/hashes.sha256"
+
+              # Extract the hash for the downloaded deb file
+              expected_hash=$(grep "$(basename "$downloadUrl")" "$tmpDir/hashes.sha256" | awk '{ print $1 }')
+
+              # Calculate the hash of the downloaded file
+              actual_hash=$(sha256sum "$tmpDir/powershell.deb" | awk '{ print $1 }')
+
+              # Compare the hashes
+              if [ "$expected_hash" != "$actual_hash" ]; then
+                  echo "Hash mismatch! Exiting."
+                  exit 1
+              else
+                  echo "Hash verified. Proceeding with installation."
+              fi
+
+              # Check if the required libicu72 is installed
+              if ! dpkg -s libicu72 &>/dev/null; then
+                  echo "libicu72 is not installed. Installing libicu72..."
+                  # Get required libicu file
+                  curl -sSL 'https://launchpad.net/ubuntu/+archive/primary/+files/libicu72_72.1-3ubuntu3_amd64.deb' -o "$tmpDir/libicu72_72.1-3ubuntu3_amd64.deb"
+                  sudo dpkg --force-confold -i "$tmpDir/libicu72_72.1-3ubuntu3_amd64.deb"
+              else
+                  echo "libicu72 is already installed."
+              fi
+
+              # Install the PowerShell package
+              echo "Installing PowerShell package..."
+              sudo dpkg -i "$tmpDir/powershell.deb"
+
+              # Resolve missing dependencies and finish the install (if necessary)
+              echo "Resolving missing dependencies..."
+              sudo apt-get install -f
+
+              # Delete the downloaded package and hash files
+              echo "Cleaning up temporary files..."
+              rm -r "$tmpDir"
+          fi
+        shell: bash
       - name: (Server) Upload IP address to shared cache
         if: ${{ matrix.role == 'server' }}
         run: |
-          $ipAddress = (Get-NetIpAddress -AddressFamily IPv4).IpAddress
+          $ipAddress = ip addr | grep 'inet ' | grep '10' | awk '{print $2}' | cut -d'/' -f1
           $headers = @{
             "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
           }
-          Invoke-WebRequest -Uri "https://netperfapiwebapp.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_ipaddress&value=$ipAddress" -Headers $headers
+          Invoke-WebRequest -Uri "https://netperfapi.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_ipaddress&value=$ipAddress" -Headers $headers -Method Post
         shell: pwsh
 
-      - name: (Server) Polls for a "done.txt" file from the client
+      - name: (Server) Checkout netperf repo
+        if: ${{ matrix.role == 'server' }}
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+        with:
+          repository: microsoft/netperf
+          ref: 'jackhe/1es-azure-pools'
+
+      - name: (Client) Checkout microsoft/msquic
+        if: ${{ matrix.role == 'client' }}
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+        with:
+          repository: microsoft/msquic
+          ref: 'jackhe/1es-azure-pools'
+
+      - name: Download Artifacts
+        uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d
+        with:
+          name: Release-linux-ubuntu-20.04-x64-openssl-Perf
+          path: artifacts
+
+      - name: (Server) Polls for client instructions
         if: ${{ matrix.role == 'server' }}
         run: |
           $found = $false
+          $headers = @{
+            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
+          }
+          $url = "https://netperfapi.azurewebsites.net"
+          $ApprovedCommandsJson = Get-Content -Path "approved-commands.json" -Raw
           do {
-              $donepath = "C:\done.txt"
-              Write-Output "Checking for done.txt..."
-              if (Test-Path $donepath) {
-                Write-Output "done.txt found"
+            try {
+              $Response = Invoke-WebRequest -Uri "$url/getkeyvalue?key=${{ github.run_id }}_state" -Headers $headers
+              $data = $Response.Content
+              if ($data -eq "done") {
                 $found = $true
                 break
-              } else {
-                Write-Output "done.txt not found"
               }
-
-              $StatePath = "C:\_state"
-              if (Test-Path $StatePath) {
-                ls $StatePath
-                # Fetch all files in the _state directory
-                $files = Get-ChildItem -Path $StatePath -File
-                # Find the highest lexicographically sorted file name
-                $max = 0
-                foreach ($file in $files) {
-                    $filename = $file.Name.split(".")[0]
-                    $num = [int]($filename -replace "[^0-9]", "")
-                    if ($num -gt $max) {
-                        $max = $num
-                    }
+              $dataJson = ConvertFrom-Json $data
+              if ($dataJson.SeqNum -lt $dataJson.Commands.Count) {
+                $command = $dataJson.Commands[$dataJson.SeqNum]
+                $dataJson.SeqNum++
+                $dataJson = @{
+                  value=$dataJson
                 }
-                # Check if there is a corresponding "completed" file
-                $ExecuteFileExist = Test-Path "$StatePath\execute_$($max).ps1"
-                $CompletedFileExist = Test-Path "$StatePath\completed_$($max).txt"
-                if ($ExecuteFileExist -and !($CompletedFileExist)) {
-                    Write-Host "Executing $StatePath\execute_$($max).ps1"
-                    Invoke-Expression "$StatePath\execute_$($max).ps1"
-                    Write-Host "Creating $StatePath\completed_$($max).txt"
-                    New-Item -ItemType File -Name "completed_$($max).txt" -Path $StatePath
+                $body = $dataJson | ConvertTo-Json
+                ls ${{ github.workspace }}
+                if ($ApprovedCommandsJson.contains($command)) {
+                  Invoke-WebRequest -Uri "$url/setkeyvalue?key=${{ github.run_id }}_state" -Headers $headers -Method POST -Body $body -ContentType "application/json"
+                  $fullPath = "${{ github.workspace }}/artifacts/bin/linux/x64_Release_openssl"
+                  $SecNetPerfPath = "$fullPath/secnetperf"
+                  $env:LD_LIBRARY_PATH = "${env:LD_LIBRARY_PATH}:$fullPath"
+                  chmod +x "$SecNetPerfPath"
+                  if ($command.contains("lowlat")) {
+                    ${{ github.workspace }}/artifacts/bin/linux/x64_Release_openssl/secnetperf -exec:lowlat -io:epoll -stats:1 | Out-Null
+                  } else {
+                    ${{ github.workspace }}/artifacts/bin/linux/x64_Release_openssl/secnetperf -exec:maxtput -io:epoll -stats:1 | Out-Null
+                  }
                 } else {
-                    Write-Host "No outstanding script to execute... Highest order script found so far: $max"
+                  Write-Output "Command not approved: $command"
                 }
+                Write-Host "Data: "
+                $dataStr = $dataJson.toString()
+                Write-Host $dataStr
               } else {
-                Write-Host "State directory not found"
+                Start-Sleep -Seconds 10
               }
-              Start-Sleep -Seconds 10
+            }
+            catch {
+              Write-Output "Client not done yet. Exit reason: $_"
+              Start-Sleep -Seconds 30
+            }
           } while (-not $found)
         shell: pwsh
 
@@ -142,7 +209,7 @@ jobs:
           $headers = @{
             "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
           }
-          $uri = "https://netperfapiwebapp.azurewebsites.net/getkeyvalue?key=${{ github.run_id }}_ipaddress"
+          $uri = "https://netperfapi.azurewebsites.net/getkeyvalue?key=${{ github.run_id }}_ipaddress"
           do {
             Write-Output "Checking for ip address..."
             try {
@@ -152,7 +219,7 @@ jobs:
               }
               $ipAddress = $Response.Content
               Write-Output "Ip Address found: $ipAddress"
-              $serverIp = $ipAddress.Split(" ") | Where-Object { $_.StartsWith("10") } | Select-Object -First 1
+              $serverIp = $ipAddress
               Write-Output "Server IP: $serverIp"
               $found = $true
             }
@@ -161,38 +228,14 @@ jobs:
               Start-Sleep -Seconds 5
             }
           } while (-not $found)
-
-          Write-Host "Preparing to run enable remote powershell session"
-          "$serverIp netperf-peer" | Out-File -Encoding ASCII -Append "$env:SystemRoot\System32\drivers\etc\hosts"
-          Set-Item WSMan:\localhost\Client\TrustedHosts -Value 'netperf-peer' -Force
-          Write-Host "$(Get-Date) Try starting a remote session"
-          Write-Host "Print powershell version information: "
-          pwsh --version
-          $Session = New-PSSession -ComputerName netperf-peer
-          $Session
-          Write-Host "Using remote powershell session to start Secnetperf"
-          Invoke-Command -Session $Session -ScriptBlock {
-            New-Item -ItemType File -Name "Sanity-check.txt" -Path "C:\"
-          }
+          Write-Host "Setting netperf-peer to $serverIp"
+          echo "$serverIp netperf-peer" | sudo tee -a /etc/hosts
         shell: pwsh
-
-      - name: (Client) Checkout microsoft/msquic
-        if: ${{ matrix.role == 'client' }}
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
-        with:
-          repository: microsoft/msquic
-          ref: 'jackhe/1es-azure-pools'
-
-      - name: (Client) Download Artifacts
-        if: ${{ matrix.role == 'client' }}
-        uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d
-        with:
-          name: Release-windows-windows-2022-x64-schannel-Perf
-          path: artifacts
 
       - name: (Client) Download Watermark_Regression.json file
         if: ${{ matrix.role == 'client' }}
         run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/microsoft/netperf/sqlite/watermark_regression.json" -OutFile "watermark_regression.json"
+        shell: pwsh
 
       - name: (Client) Run Secnetperf Script
         if: ${{ matrix.role == 'client' }}
@@ -202,17 +245,20 @@ jobs:
             -LogProfile 'NULL' `
             -MsQuicCommit 'TODO' `
             -environment 'azure' `
-            -plat 'windows' `
-            -os 'windows-2022' `
+            -plat 'linux' `
+            -os 'ubuntu-18.04' `
             -arch 'x64' `
-            -tls 'schannel' `
-            -io 'iocp' `
+            -tls 'openssl' `
+            -io 'epoll' `
             -filter ''
-      - name: (Client) Creates a 'done.txt' file to signal the server
+            -RemotePowershellSupported 'FALSE'
+            -RunId ${{ github.run_id }}_state
+            -SyncerSecret ${{ secrets.NETPERF_SYNCER_SECRET }}
+      - name: (Client) Uploads ACK to shared cache
         if: ${{ matrix.role == 'client' }}
         run: |
-          $Session = New-PSSession -ComputerName netperf-peer
-          Invoke-Command -Session $Session -ScriptBlock {
-            New-Item -ItemType File -Name "done.txt" -Path "C:\"
+          $headers = @{
+            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
           }
+          Invoke-WebRequest -Uri "https://netperfapi.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_state&value=done" -Headers $headers -Method Post
         shell: pwsh
