wip

diff --git a/.github/workflows/custom.yml b/.github/workflows/custom.yml
--- a/.github/workflows/custom.yml
+++ b/.github/workflows/custom.yml
@@ -1,4 +1,7 @@
 name: Custom Tasks
+# Physical lab machine has multiple VMs.
+# Run this once every day.
+# Notify via email if something fails.
 
 on:
   workflow_call:
@@ -17,3 +20,97 @@ jobs:
     permissions:
       security-events: write  # For CodeQL
     uses: microsoft/xdp-for-windows/.github/workflows/build_matrix.yml@main
+
+  stress_tests:
+    name: Stress Tests
+    needs: build
+    env:
+      successThresholdPercent: 1
+      xdpmpPollProvider: 'FNDIS'
+      # For 'main' commits
+      fullRuntime: 5 # minutes. Update timeout-minutes with any changes.
+    strategy:
+      fail-fast: false
+      matrix:
+        windows: [2022]
+        configuration: [Debug]
+        platform: [x64]
+        testDriver: [FNMP]
+        enableTxInspect: [disableTxInspect]
+        exclude:
+        - testDriver: FNMP
+          enableTxInspect: enableTxInspect
+    timeout-minutes: 155
+    runs-on:
+     - self-hosted
+     - lab
+     - Windows
+     - SpinXsk
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
+      with:
+        repo: microsoft/xdp-for-windows
+        sparse-checkout: tools
+    - name: Check Drivers
+      shell: PowerShell
+      run: tools/check-drivers.ps1 -Config ${{ matrix.configuration }} -Platform ${{ matrix.platform }} -Verbose
+    - name: Prepare Machine
+      shell: PowerShell
+      run: tools/prepare-machine.ps1 -ForSpinxskTest -Platform ${{ matrix.platform }} -RequireNoReboot -Verbose
+    - name: Download Artifacts
+      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
+      with:
+        name: bin_${{ matrix.configuration }}_${{ matrix.platform }}
+        path: artifacts/bin
+    - name: Run spinxsk (with TxInspect)
+      if: ${{ matrix.testDriver == 'XDPMP' && matrix.enableTxInspect == 'enableTxInspect' }}
+      shell: PowerShell
+      timeout-minutes: 70
+      run: tools/spinxsk.ps1 -Verbose -Stats -Config ${{ matrix.configuration }} -Platform ${{ matrix.platform }} -Driver ${{ matrix.testDriver}} -Minutes ${{ env.fullRuntime }} -XdpmpPollProvider ${{ env.xdpmpPollProvider }} -SuccessThresholdPercent ${{ env.successThresholdPercent }} -EnableEbpf -XdpInstaller NuGet -TxInspect
+    - name: Run spinxsk (without TxInspect)
+      if: ${{ matrix.enableTxInspect == 'disableTxInspect' }}
+      shell: PowerShell
+      timeout-minutes: 70
+      run: tools/spinxsk.ps1 -Verbose -Stats -Config ${{ matrix.configuration }} -Platform ${{ matrix.platform }} -Driver ${{ matrix.testDriver}} -Minutes ${{ env.fullRuntime }} -XdpmpPollProvider ${{ env.xdpmpPollProvider }} -SuccessThresholdPercent ${{ env.successThresholdPercent }} -EnableEbpf -XdpInstaller NuGet
+    - name: Convert Logs
+      if: ${{ always() }}
+      timeout-minutes: 15
+      shell: PowerShell
+      run: tools/log.ps1 -Convert -Name spinxsk_${{ matrix.testDriver }} -Verbose -Config ${{ matrix.configuration }} -Platform ${{ matrix.platform }}
+    - name: Upload Logs
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
+      if: ${{ always() }}
+      with:
+        name: logs_stress_win${{ matrix.windows }}_${{ matrix.configuration }}_${{ matrix.platform }}_${{ matrix.testDriver }}_${{ matrix.enableTxInspect }}
+        path: artifacts/logs
+    - name: Check Drivers
+      if: ${{ always() }}
+      shell: PowerShell
+      run: tools/check-drivers.ps1 -Config ${{ matrix.configuration }} -Platform ${{ matrix.platform }} -Verbose
+
+  collect_crashdump_if_any:
+    name: Collect Crashdump If Any
+    needs: [bvt-kernel]
+    if: failure()
+    runs-on:
+      - self-hosted
+      - lab
+      - Windows
+      - SpinXsk
+    steps:
+      - name: Sanity Check
+        run: |
+          if (Test-Path 'C:\Windows\MEMORY.DMP') {
+            Write-Host "Crash dump found."
+            cp 'C:\Windows\MEMORY.DMP' .
+          } else {
+            Write-Host "No crash dump found."
+            exit 1
+          }
+        shell: pwsh
+      - name: Upload Crashdump
+        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
+        with:
+          name: memorydmp
+          path: MEMORY.DMP
