parent does not wait

diff --git a/.github/workflows/operate-lab.yml b/.github/workflows/operate-lab.yml
--- a/.github/workflows/operate-lab.yml
+++ b/.github/workflows/operate-lab.yml
@@ -88,60 +88,60 @@ jobs:
             Write-Host "Failed to alert observer of parent reset completion: $_"
             exit 1
           }
-      - name: Grab workflow ID of callee from the truth table
-        run: |
-          $headers = @{
-            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
-          }
-          $key = "${{ github.run_id }}_${{ github.run_attempt }}_truth_table"
-          $done = $false
-          $attempts = 0
-          while (!$done) {
-            $attempts++
-            try {
-              $api = "https://netperfapi.azurewebsites.net/getkeyvalue?key=$key"
-              $response = Invoke-WebRequest -Uri $api -Headers $headers -Method Get
-              if ($response.StatusCode -ne 200) {
-                throw "Failed to grab truth table: $response"
-              }
-              $truth_table = ConvertFrom-Json $response.Content
-              foreach ($row in $truth_table) {
-                if ($row.job.env_str.Contains("${{ matrix.env_str }}")) {
-                  Write-Host "Found matching row in truth table."
-                  if ($row.dispatched_workflow_id) {
-                    $callee_workflow_id = $row.dispatched_workflow_id
-                    echo "CalleeWorkflowId=$callee_workflow_id" >> $env:GITHUB_ENV
-                    $done = $true
-                  }
-                }
-              }
-            } catch {
-              Write-Host "Failed to grab callee workflow ID from truth table: $_"
-            }
-            if (!$done -and $attempts -gt 36) {
-              Write-Host "Failed to grab callee workflow ID from truth table after 12 minutes."
-              exit 1
-            }
-            Start-Sleep -Seconds 20
-          }
+      # - name: Grab workflow ID of callee from the truth table
+      #   run: |
+      #     $headers = @{
+      #       "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
+      #     }
+      #     $key = "${{ github.run_id }}_${{ github.run_attempt }}_truth_table"
+      #     $done = $false
+      #     $attempts = 0
+      #     while (!$done) {
+      #       $attempts++
+      #       try {
+      #         $api = "https://netperfapi.azurewebsites.net/getkeyvalue?key=$key"
+      #         $response = Invoke-WebRequest -Uri $api -Headers $headers -Method Get
+      #         if ($response.StatusCode -ne 200) {
+      #           throw "Failed to grab truth table: $response"
+      #         }
+      #         $truth_table = ConvertFrom-Json $response.Content
+      #         foreach ($row in $truth_table) {
+      #           if ($row.job.env_str.Contains("${{ matrix.env_str }}")) {
+      #             Write-Host "Found matching row in truth table."
+      #             if ($row.dispatched_workflow_id) {
+      #               $callee_workflow_id = $row.dispatched_workflow_id
+      #               echo "CalleeWorkflowId=$callee_workflow_id" >> $env:GITHUB_ENV
+      #               $done = $true
+      #             }
+      #           }
+      #         }
+      #       } catch {
+      #         Write-Host "Failed to grab callee workflow ID from truth table: $_"
+      #       }
+      #       if (!$done -and $attempts -gt 36) {
+      #         Write-Host "Failed to grab callee workflow ID from truth table after 12 minutes."
+      #         exit 1
+      #       }
+      #       Start-Sleep -Seconds 20
+      #     }
 
-      - name: Wait-Callee_${{ env.CalleeWorkflowId }}
-        run: |
-          $headers = @{
-            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
-          }
-          $url = "https://api.github.com/repos/microsoft/netperf/actions/runs/${{ env.CalleeWorkflowId }}"
-          while ($true) {
-            $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get
-            $run_status = ConvertFrom-Json $response.Content
-            if ($run_status.status -eq "completed") {
-              if ($run_status.conclusion -eq "success") {
-                Write-Host "Callee workflow completed successfully."
-                break
-              } else {
-                Write-Host "Callee workflow failed."
-                exit 1
-              }
-            }
-            Start-Sleep -Seconds 30
-          }
+      # - name: Wait-Callee_${{ env.CalleeWorkflowId }}
+      #   run: |
+      #     $headers = @{
+      #       "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
+      #     }
+      #     $url = "https://api.github.com/repos/microsoft/netperf/actions/runs/${{ env.CalleeWorkflowId }}"
+      #     while ($true) {
+      #       $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get
+      #       $run_status = ConvertFrom-Json $response.Content
+      #       if ($run_status.status -eq "completed") {
+      #         if ($run_status.conclusion -eq "success") {
+      #           Write-Host "Callee workflow completed successfully."
+      #           break
+      #         } else {
+      #           Write-Host "Callee workflow failed."
+      #           exit 1
+      #         }
+      #       }
+      #       Start-Sleep -Seconds 30
+      #     }
